name: "QA"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: stagging
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.12'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint scan
      run: |
        npx eslint . --ext .js,.jsx --format junit --output-file eslint-results.xml \
          --ignore-pattern "/contract/**" --ignore-pattern "apps/**/src/models/**"
      continue-on-error: true

    - name: Publish ESLint results
      uses: mikepenz/action-junit-report@v4
      with:
        report_paths: 'eslint-results.xml'
        fail_on_failure: true
    - name: Build and Push
      run: |
        id
        env
        sudo apt-get update
        echo "${{ secrets.ALICLOUD_REGISTRY_PASSWORD }}" | helm registry login -u ${{ vars.ALICLOUD_REGISTRY_USERNAME }}@${{ vars.ALICLOUD_ACCOUNT_ID }} ${{ vars.ALICLOUD_REGISTRY }}
        tar -czvf ./charts/clienteling-backend.tgz ./charts/clienteling-backend
        helm push ./charts/clienteling-backend.tgz oci://${{ vars.ALICLOUD_REGISTRY }}/${{ vars.ALICLOUD_REGISTRY_QA_NAMESPACE }}

